export const categories = [
    { id: 1, name: 'Lập trình', icon: 'MonitorPlay', color: '#3B82F6', bgColor: '#EFF6FF' },
    { id: 2, name: 'Thiết kế', icon: 'PenTool', color: '#8B5CF6', bgColor: '#F5F3FF' },
    { id: 3, name: 'Marketing', icon: 'Lightbulb', color: '#F59E0B', bgColor: '#FFFBEB' },
    { id: 4, name: 'Kinh doanh', icon: 'Briefcase', color: '#10B981', bgColor: '#ECFDF5' },
    { id: 5, name: 'Ngoại ngữ', icon: 'Languages', color: '#EF4444', bgColor: '#FEF2F2' },
    { id: 6, name: 'Bản thân', icon: 'Sparkles', color: '#EC4899', bgColor: '#FDF2F8' },
    { id: 7, name: 'Tài chính', icon: 'TrendingUp', color: '#06B6D4', bgColor: '#CFFAFE' },
    { id: 8, name: 'Nhiếp ảnh', icon: 'Camera', color: '#F97316', bgColor: '#FFEDD5' },
];

export const courses = [
    {
        id: 1,
        title: 'React Native - Xây dựng app từ đầu',
        instructor: 'Nguyễn Văn An',
        price: '499.000đ',
        originalPrice: '799.000đ',
        rating: 4.8,
        reviewCount: 1240,
        studentCount: 8500,
        thumbnail: 'https://picsum.photos/seed/rn1/400/220',
        category: 'Lập trình',
        badge: 'Bán chạy',
        duration: '24 giờ',
        level: 'Trung cấp',
        description: 'Khóa học toàn diện về React Native, từ cơ bản đến nâng cao. Bạn sẽ xây dựng được 5 ứng dụng thực tế và nắm vững các kỹ thuật phát triển mobile hiện đại.',
        curriculum: [
            { section: 'Giới thiệu', lessons: 4 },
            { section: 'Components cơ bản', lessons: 12 },
            { section: 'Navigation', lessons: 8 },
            { section: 'State Management', lessons: 10 },
            { section: 'API & Networking', lessons: 7 },
        ],
    },
    {
        id: 2,
        title: 'UI/UX Design - Figma Masterclass',
        instructor: 'Trần Thị Bích',
        price: '399.000đ',
        originalPrice: '699.000đ',
        rating: 4.9,
        reviewCount: 980,
        studentCount: 6200,
        thumbnail: 'https://picsum.photos/seed/ux2/400/220',
        category: 'Thiết kế',
        badge: 'Mới',
        duration: '18 giờ',
        level: 'Cơ bản',
        description: 'Học thiết kế UI/UX chuyên nghiệp với Figma. Từ wireframe đến prototype hoàn chỉnh, bạn sẽ tạo ra các giao diện đẹp và trải nghiệm người dùng tuyệt vời.',
        curriculum: [
            { section: 'Figma cơ bản', lessons: 6 },
            { section: 'Design System', lessons: 9 },
            { section: 'Prototyping', lessons: 7 },
            { section: 'User Testing', lessons: 5 },
        ],
    },
    {
        id: 3,
        title: 'Digital Marketing 2024 - Từ A đến Z',
        instructor: 'Lê Hoàng Nam',
        price: '299.000đ',
        originalPrice: '599.000đ',
        rating: 4.6,
        reviewCount: 756,
        studentCount: 4300,
        thumbnail: 'https://picsum.photos/seed/mkt3/400/220',
        category: 'Marketing',
        badge: null,
        duration: '20 giờ',
        level: 'Cơ bản',
        description: 'Khóa học Digital Marketing toàn diện bao gồm SEO, Google Ads, Facebook Ads, Content Marketing và phân tích dữ liệu.',
        curriculum: [
            { section: 'SEO cơ bản', lessons: 8 },
            { section: 'Google Ads', lessons: 10 },
            { section: 'Facebook Ads', lessons: 9 },
            { section: 'Analytics', lessons: 6 },
        ],
    },
    {
        id: 4,
        title: 'Python cho Data Science',
        instructor: 'Phạm Minh Tuấn',
        price: '599.000đ',
        originalPrice: '999.000đ',
        rating: 4.7,
        reviewCount: 1580,
        studentCount: 12000,
        thumbnail: 'https://picsum.photos/seed/py4/400/220',
        category: 'Lập trình',
        badge: 'Bán chạy',
        duration: '32 giờ',
        level: 'Nâng cao',
        description: 'Làm chủ Python để phân tích dữ liệu, xây dựng mô hình Machine Learning và trực quan hóa dữ liệu với pandas, numpy, matplotlib và scikit-learn.',
        curriculum: [
            { section: 'Python cơ bản', lessons: 10 },
            { section: 'Pandas & Numpy', lessons: 12 },
            { section: 'Machine Learning', lessons: 15 },
            { section: 'Deep Learning', lessons: 8 },
        ],
    },
    {
        id: 5,
        title: 'IELTS Speaking & Writing 7.0+',
        instructor: 'Hoàng Thị Mai',
        price: '449.000đ',
        originalPrice: '749.000đ',
        rating: 4.8,
        reviewCount: 892,
        studentCount: 5600,
        thumbnail: 'https://picsum.photos/seed/ielts5/400/220',
        category: 'Ngoại ngữ',
        badge: 'Nổi bật',
        duration: '28 giờ',
        level: 'Trung cấp',
        description: 'Nâng band IELTS lên 7.0+ với chiến lược học tập thông minh. Khóa học bao gồm Speaking templates, Writing task 1 & 2 và luyện đề thực tế.',
        curriculum: [
            { section: 'Speaking Part 1', lessons: 6 },
            { section: 'Speaking Part 2 & 3', lessons: 8 },
            { section: 'Writing Task 1', lessons: 10 },
            { section: 'Writing Task 2', lessons: 12 },
        ],
    },
    {
        id: 6,
        title: 'Vue.js 3 - Thực chiến',
        instructor: 'Đặng Quốc Hùng',
        price: '379.000đ',
        originalPrice: '649.000đ',
        rating: 4.5,
        reviewCount: 430,
        studentCount: 2800,
        thumbnail: 'https://picsum.photos/seed/vue6/400/220',
        category: 'Lập trình',
        badge: 'Mới',
        duration: '16 giờ',
        level: 'Trung cấp',
        description: 'Khóa học Vue.js 3 từ composition API đến Pinia state management, xây dựng ứng dụng full-featured với Vue Router và Vite.',
        curriculum: [
            { section: 'Vue 3 Composition API', lessons: 8 },
            { section: 'Vue Router', lessons: 6 },
            { section: 'Pinia', lessons: 7 },
            { section: 'Project thực tế', lessons: 5 },
        ],
    },
];

export const featuredCourses = courses.filter(c => c.badge !== null);

export const myCourses = [
    { ...courses[0], progress: 65, lastLesson: 'Navigation - Lesson 3' },
    { ...courses[1], progress: 30, lastLesson: 'Figma cơ bản - Lesson 4' },
    { ...courses[4], progress: 100, lastLesson: 'Hoàn thành', completed: true },
];
