spring.application.name=gnostica-server

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/gnostica-database
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driverClassName=org.postgresql.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Spring Mail (Gmail) Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=awakamayuki@gmail.com
spring.mail.password=hjlnvnuymhejsebp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Google configuration
spring.security.oauth2.client.registration.google.client-id=1020861494257-1nmlgfd2u67dh5lid86lo4sg16573cvb.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email

# Core PayOS credentials
payos.client-id=a19996cf-974f-4d32-ab93-54754530c596
payos.api-key=25e1146d-76db-4e9a-abf0-e3b558813ea7
payos.checksum-key=bdc33b29007da4048b15ee43bd8eaffd0293939e42929ff126bc9648a087b3cb

# Optional: Payout credentials
payos.payout-client-id=35838a0d-742b-40ea-998c-ba526e34c00f
payos.payout-api-key=4b0c023f-2898-4e4f-9264-7fefdc8f08a8
payos.payout-checksum-key=c73759b2caa5128acd720faf1b191b1370933165ce40cb9b54b3bb89544f1651

# Logging level: DEBUG | INFO | NONE
payos.log-level=NONE
app.jwt.secret=your_very_long_and_secure_random_secret_key_here
app.jwt.expiration=86400000

# Cloudinary Configuration
cloudinary.cloud-name=dpzvnjchx
cloudinary.api-key=489979921882123
cloudinary.api-secret=fZzomzqIyImz4MjMKgG_DU1n0vU

# File Upload configuration
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB
