spring.application.name=gnostica-server

spring.datasource.url=jdbc:sqlserver://localhost:1433;database=gnostica;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Spring Mail (Gmail) Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=awakamayuki@gmail.com
spring.mail.password=hjlnvnuymhejsebp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# OAuth2 (Google/Facebook)
# Google configuration
spring.security.oauth2.client.registration.google.client-id=1020861494257-1nmlgfd2u67dh5lid86lo4sg16573cvb.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email

# Facebook configuration
spring.security.oauth2.client.registration.facebook.client-id=YOUR-FACEBOOK-APP-ID
spring.security.oauth2.client.registration.facebook.client-secret=YOUR-FACEBOOK-APP-SECRET
spring.security.oauth2.client.registration.facebook.scope=public_profile,email