spring.application.name=gnostica-server

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/gnostica-database
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driverClassName=org.postgresql.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Spring Mail (Gmail) Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=awakamayuki@gmail.com
spring.mail.password=hjlnvnuymhejsebp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Google configuration
spring.security.oauth2.client.registration.google.client-id=1020861494257-1nmlgfd2u67dh5lid86lo4sg16573cvb.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email

# Sửa lại cho đúng với JwtProvider.java
app.jwt.secret=your_very_long_and_secure_random_secret_key_here
app.jwt.expiration=86400000

