-- Gnostica account seed: 1,000 local-login demo accounts
--
-- Scope: accounts only. It requires the active USER and INSTRUCTOR roles that
-- Flyway V1 creates. No ADMIN account is created or modified.
--
-- Login password for every inserted account: Test@123
-- The value below is a BCrypt hash generated by Spring Security's
-- BCryptPasswordEncoder; the plaintext password is never stored.

BEGIN;

CREATE TEMP TABLE seed_context (
    run_id UUID PRIMARY KEY
) ON COMMIT DROP;

DO $$
BEGIN
    IF to_regclass('public.seed_runs') IS NULL OR to_regclass('public.seed_run_items') IS NULL THEN
        RAISE EXCEPTION 'Missing seed journal. Run seed_00_seed_journal.sql before this script.';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM roles WHERE name = 'USER' AND status = 1) THEN
        RAISE EXCEPTION 'Missing active USER role. Apply the database migrations before running this seed.';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM roles WHERE name = 'INSTRUCTOR' AND status = 1) THEN
        RAISE EXCEPTION 'Missing active INSTRUCTOR role. Apply the database migrations before running this seed.';
    END IF;

    IF EXISTS (SELECT 1 FROM accounts WHERE metadata ->> 'seed_batch' = 'gnostica-account-v1') THEN
        RAISE EXCEPTION 'Account seed gnostica-account-v1 already exists. Do not run this script twice.';
    END IF;
END $$;

WITH new_run AS (
    INSERT INTO seed_runs (id, seed_name, status, metadata, created_at)
    VALUES (
        gen_random_uuid(),
        'seed_01_account_data.sql',
        'RUNNING',
        jsonb_build_object('seed_batch', 'gnostica-account-v1', 'expected_records', 1000),
        NOW()
    )
    RETURNING id
)
INSERT INTO seed_context (run_id)
SELECT id FROM new_run;

-- 950 learners (USER) and 50 instructors (INSTRUCTOR). The email local part
-- combines three real-name components, not a sequential account number. There
-- are 5,000 possible combinations; this batch uses 1,000 unique combinations.
WITH name_parts AS (
    SELECT
        ARRAY['Nguyễn', 'Trần', 'Lê', 'Phạm', 'Hoàng', 'Huỳnh', 'Võ', 'Đặng', 'Bùi', 'Đỗ',
              'Hồ', 'Ngô', 'Dương', 'Lý', 'Đinh', 'Vũ', 'Cao', 'Tạ', 'Mai', 'Tô',
              'Chu', 'La', 'Quách', 'Thái', 'Trương']::TEXT[] AS family_names,
        ARRAY['Minh', 'Thị', 'Thanh', 'Quốc', 'Ngọc', 'Gia', 'Bảo', 'Khánh', 'Phương', 'Hữu']::TEXT[] AS middle_names,
        ARRAY['An', 'Anh', 'Bình', 'Châu', 'Duy', 'Giang', 'Hân', 'Huy', 'Khang', 'Lan',
              'Linh', 'Long', 'Mai', 'Nam', 'Ngọc', 'Nhi', 'Phúc', 'Quân', 'Trang', 'Vy',
              'Ánh', 'Bách', 'Cường', 'Diễm', 'Đạt', 'Hà', 'Hiếu', 'Kiên', 'Liên', 'Minh',
              'My', 'Nhân', 'Oanh', 'Quỳnh', 'Sơn', 'Tài', 'Thảo', 'Thuận', 'Trí', 'Tú',
              'Uyên', 'Vân', 'Việt', 'Xuân', 'Yến', 'Yên', 'Lộc', 'Lợi', 'Mẫn', 'Nghĩa']::TEXT[] AS given_names,
        ARRAY['nguyen', 'tran', 'le', 'pham', 'hoang', 'huynh', 'vo', 'dang', 'bui', 'do',
              'ho', 'ngo', 'duong', 'ly', 'dinh', 'vu', 'cao', 'ta', 'mai', 'to',
              'chu', 'la', 'quach', 'thai', 'truong']::TEXT[] AS email_family_names,
        ARRAY['minh', 'thi', 'thanh', 'quoc', 'ngoc', 'gia', 'bao', 'khanh', 'phuong', 'huu']::TEXT[] AS email_middle_names,
        ARRAY['an', 'anh', 'binh', 'chau', 'duy', 'giang', 'han', 'huy', 'khang', 'lan',
              'linh', 'long', 'mai', 'nam', 'ngoc', 'nhi', 'phuc', 'quan', 'trang', 'vy']::TEXT[] AS email_given_names
), seed_roles AS (
    SELECT name, id FROM roles WHERE name IN ('USER', 'INSTRUCTOR') AND status = 1
), generated_keys AS (
    SELECT n, ((n * 37 + 71) % 5000)::INT AS name_key
    FROM generate_series(1, 1000) AS n
), generated_accounts AS (
    SELECT
        n,
        family_names[1 + (name_key % 25)] AS family_name,
        middle_names[1 + ((name_key / 25) % 10)] AS middle_name,
        given_names[1 + ((n * 23 + 7) % 50)] AS given_name,
        email_family_names[1 + (name_key % 25)] AS email_family_name,
        email_middle_names[1 + ((name_key / 25) % 10)] AS email_middle_name,
        email_given_names[1 + ((name_key / 250) % 20)] AS email_given_name,
        (ARRAY['032', '033', '034', '035', '036', '037', '038', '039', '070', '076',
               '077', '078', '079', '081', '082', '083', '084', '085', '086', '088',
               '089', '090', '091', '092', '093', '094', '096', '097', '098', '099']::TEXT[])[1 + ((n * 13 + 3) % 30)] AS phone_prefix
    FROM generated_keys
    CROSS JOIN name_parts
), inserted_accounts AS (
    INSERT INTO accounts (
        id, role_id, email, full_name, phone, password, avatar, provider, birth_day,
        metadata, status, created_at, updated_at, deleted_at
    )
    SELECT
        gen_random_uuid(),
        role.id,
        a.email_given_name || a.email_middle_name || a.email_family_name || '@gmail.com',
        a.family_name || ' ' || a.middle_name || ' ' || a.given_name,
        CASE WHEN a.n % 7 = 0 THEN NULL
             ELSE a.phone_prefix || lpad(((a.n * 7919 + 123457) % 10000000)::TEXT, 7, '0')
        END,
        '$2a$10$bbFQV79lXECRuAT8vZUyzuWjzsyeePG7aiL.CeFSESm9Plwj0RBVK',
        CASE WHEN a.n % 5 = 0 THEN NULL
             ELSE 'https://api.dicebear.com/9.x/initials/svg?seed=' || a.email_given_name || '-' || a.email_middle_name || '-' || a.email_family_name
        END,
        'EMAIL',
        CASE WHEN a.n % 4 = 0 THEN NULL
             ELSE DATE '1964-01-01' + ((a.n * 137 + 7919) % 16802)
        END,
        jsonb_build_object(
            'seed_batch', 'gnostica-account-v1',
            'account_kind', CASE WHEN a.n <= 950 THEN 'learner' ELSE 'instructor' END,
            'activity_segment', CASE WHEN a.n % 11 = 0 THEN 'low_activity' WHEN a.n % 4 = 0 THEN 'high_activity' ELSE 'regular' END,
            'login_method', 'local'
        ),
        CASE
            WHEN a.n BETWEEN 801 AND 900 OR a.n BETWEEN 991 AND 995 THEN 0 -- unverified
            WHEN a.n BETWEEN 901 AND 930 OR a.n BETWEEN 996 AND 998 THEN 2 -- banned
            WHEN a.n BETWEEN 931 AND 950 OR a.n BETWEEN 999 AND 1000 THEN 3 -- soft deleted
            ELSE 1 -- active
        END,
        NOW() - (30 + ((a.n * 19) % 1000)) * INTERVAL '1 day',
        NOW() - (10 + ((a.n * 19) % 1000)) * INTERVAL '1 day',
        CASE WHEN a.n BETWEEN 931 AND 950 OR a.n BETWEEN 999 AND 1000
             THEN NOW() - ((a.n % 20) + 1) * INTERVAL '1 day'
             ELSE NULL END
    FROM generated_accounts a
    JOIN seed_roles role ON role.name = CASE WHEN a.n <= 950 THEN 'USER' ELSE 'INSTRUCTOR' END
    RETURNING id
)
INSERT INTO seed_run_items (run_id, table_name, record_id)
SELECT c.run_id, 'accounts', a.id::TEXT
FROM inserted_accounts a
CROSS JOIN seed_context c;

-- Verification report. Expected totals: 950 USER + 50 INSTRUCTOR = 1,000.
SELECT
    r.name AS role,
    a.status,
    count(*) AS accounts_created
FROM accounts a
JOIN roles r ON r.id = a.role_id
WHERE a.metadata ->> 'seed_batch' = 'gnostica-account-v1'
GROUP BY r.name, a.status
ORDER BY r.name, a.status;

SELECT
    count(*) AS total_accounts,
    count(DISTINCT email) AS unique_emails,
    count(DISTINCT phone) AS unique_phones,
    count(*) FILTER (WHERE phone IS NULL) AS missing_phones,
    count(*) FILTER (WHERE avatar IS NULL) AS missing_avatars,
    count(*) FILTER (WHERE birth_day IS NULL) AS missing_birth_days
FROM accounts
WHERE metadata ->> 'seed_batch' = 'gnostica-account-v1';

UPDATE seed_runs
SET status = 'COMPLETED', completed_at = NOW()
WHERE id = (SELECT run_id FROM seed_context);

COMMIT;
